### ISSUE TITLE
{FRONT-END] - Alteração do componente Input password, modificação do tema do Header e criação do Modal

### ISSUE THREAD

**Issue by Paul0Ant0ni0** [lufedev/orange-portfolio#24]
- [ ] Reutilizar o input password do Material UI para modificar o componente LoginInput da Task #12 e #15 <br><br>
- [ ] Criar e configurar o Tema do componente Header da Task #10 
- [ ] Criar o Modal da Task #23
